Repository WildCodeSchool/orleans-202103-php-project-bretin, pull requests merged in 2021-06, with the labels that each got.

#22 navbar creation
  assets/images/logo.png
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/Includes/_navbar.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: Reviewed

#23 Init-Navbar
  assets/app.js
  assets/images/logo.png
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/Includes/_navbar.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  yarn.lock
Labels: Reviewed

#37 S03_US01_Footer
  assets/images/Logo_L.Bretinrogn.png
  assets/images/loicprofil.png
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/variables.scss
  templates/Includes/_footer.html.twig
  templates/layout.html.twig
Labels: Reviewed

#41 Merge footer from dev to master
  assets/images/Logo_L.Bretinrogn.png
  assets/images/loicprofil.png
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/variables.scss
  templates/Includes/_footer.html.twig
  templates/layout.html.twig
Labels: Reviewed

#35 fix button class RDV
  assets/styles/app.scss
  templates/Includes/_navbar.html.twig
Labels: Corrections done, Reviewed

#43 S03 us04 story
  assets/images/loic.png
  assets/styles/app.scss
  assets/styles/variables.scss
  migrations/Version20210608134923.php
  src/Controller/HomeController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/home/index.html.twig
  templates/includes/_story.html.twig
Labels: Reviewed

#39 Contact
  composer.json
  composer.lock
  migrations/Version20210616094701.php
  src/Controller/ContactController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/OfficeFixtures.php
  src/Entity/Office.php
  src/Repository/OfficeRepository.php
  templates/home/contact.html.twig
Labels: Corrections done, Reviewed

#44 Fix contact
  migrations/Version20210616140824.php
  src/DataFixtures/OfficeFixtures.php
  src/Entity/Office.php
  templates/home/contact.html.twig
Labels: Corrections done, Reviewed

#45 section education
  src/Controller/HomeController.php
  src/DataFixtures/EducationFixtures.php
  src/Entity/Education.php
  src/Repository/EducationRepository.php
  templates/Components/_education.html.twig
  templates/Components/_story.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#46 Section présentation accueil
  assets/images/background-sofa.jpg
  assets/styles/accueil.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/Includes/_accueil.html.twig
  templates/Includes/_navbar.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: Conflit résolu, Reviewed

#48 Contact picture
  migrations/Version20210617115735.php
  public/uploads/cabinet1.jpg
  public/uploads/cabinet2.jpg
  public/uploads/cabinet21.jpg
  public/uploads/cabinet22.jpg
  public/uploads/cabinet23.jpg
  public/uploads/cabinet3.jpg
  src/DataFixtures/OfficeFixtures.php
  src/DataFixtures/PictureFixtures.php
  src/Entity/Office.php
  src/Entity/Picture.php
  src/Repository/PictureRepository.php
  templates/home/contact.html.twig
Labels: Corrections done, Reviewed

#50 upgrade page home and contact
  assets/images/background-sofa.jpg
  assets/images/loic.png
  assets/styles/accueil.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20210608134923.php
  migrations/Version20210617115735.php
  public/uploads/cabinet1.jpg
  public/uploads/cabinet2.jpg
  public/uploads/cabinet21.jpg
  public/uploads/cabinet22.jpg
  public/uploads/cabinet23.jpg
  public/uploads/cabinet3.jpg
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/EducationFixtures.php
  src/DataFixtures/OfficeFixtures.php
  src/DataFixtures/PictureFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Education.php
  src/Entity/Office.php
  src/Entity/Picture.php
  src/Entity/User.php
  src/Repository/EducationRepository.php
  src/Repository/OfficeRepository.php
  src/Repository/PictureRepository.php
  src/Repository/UserRepository.php
  templates/Components/_education.html.twig
  templates/Components/_story.html.twig
  templates/Includes/_accueil.html.twig
  templates/Includes/_navbar.html.twig
  templates/base.html.twig
  templates/home/contact.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: Reviewed

#51 services section
  assets/images/candle.png
  assets/styles/individuals.scss
  src/Controller/IndividualsController.php
  templates/Individuals/index.html.twig
  webpack.config.js
Labels: Reviewed

#52 fix contact pictures
  migrations/Version20210608134923.php
  migrations/Version20210617164024.php
  src/Controller/ContactController.php
  templates/Contact/People/contact.html.twig
  templates/Includes/_contact.html.twig
  templates/home/contact.html.twig
Labels: Reviewed

#54 fix migration
  migrations/Version20210618082502.php
Labels: Reviewed

#55 dev to master
  assets/images/candle.png
  assets/styles/individuals.scss
  migrations/Version20210608134923.php
  migrations/Version20210618082502.php
  src/Controller/ContactController.php
  src/Controller/IndividualsController.php
  templates/Contact/People/contact.html.twig
  templates/Includes/_contact.html.twig
  templates/Individuals/index.html.twig
  templates/home/contact.html.twig
  webpack.config.js
Labels: Reviewed

#78 modif style
  assets/styles/individuals.scss
  assets/styles/variables.scss
  templates/Individuals/index.html.twig
Labels: Reviewed

#75 Fix presentation
  assets/images/stones-activity.png
  assets/styles/accueil.scss
  assets/styles/activity.scss
  assets/styles/app.scss
  migrations/Version20210621082508.php
  templates/Components/_activity.html.twig
  templates/Components/_story.html.twig
  templates/Includes/_accueil.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#79 S4 us19 testimony entity fixtures
  composer.json
  composer.lock
  migrations/Version20210621082508.php
  migrations/Version20210621204553.php
  src/DataFixtures/TestimonyFixtures.php
  src/Entity/Testimony.php
  src/Repository/TestimonyRepository.php
  symfony.lock
  templates/Components/_story.html.twig
  templates/Individuals/index.html.twig
Labels: Conflit résolu, Reviewed

#84 Dev to Master
  assets/images/address.svg
  assets/images/calendar-date.svg
  assets/images/envelope.svg
  assets/images/stones-activity.png
  assets/images/tel.svg
  assets/styles/accueil.scss
  assets/styles/activity.scss
  assets/styles/app.scss
  assets/styles/contact.scss
  assets/styles/individuals.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20210621204553.php
  src/DataFixtures/OfficeFixtures.php
  src/DataFixtures/TestimonyFixtures.php
  src/Entity/Testimony.php
  src/Repository/TestimonyRepository.php
  symfony.lock
  templates/Components/_activity.html.twig
  templates/Contact/People/contact.html.twig
  templates/Includes/_accueil.html.twig
  templates/Includes/_contact.html.twig
  templates/Individuals/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#85 Fix4 navbar
  assets/styles/app.scss
Labels: Reviewed

#88 Fix story
  assets/styles/app.scss
  assets/styles/story.scss
  assets/styles/variables.scss
  src/DataFixtures/UserFixtures.php
  templates/Components/_story.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#87 Admin ajout coordonnées
  assets/styles/contact.scss
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/packages/translation.yaml
  migrations/Version20210624083134.php
  src/Controller/CabinetController.php
  src/DataFixtures/OfficeFixtures.php
  src/Entity/Office.php
  src/Form/OfficeType.php
  templates/Contact/People/Admin/add_office.html.twig
  templates/cabinet/_delete_form.html.twig
  templates/cabinet/_form.html.twig
  templates/cabinet/edit.html.twig
  templates/cabinet/index.html.twig
  templates/cabinet/new.html.twig
  templates/cabinet/show.html.twig
Labels: Corrections done, Reviewed

#91 fix section education
  assets/styles/app.scss
  assets/styles/education.scss
  templates/Components/_education.html.twig
  templates/Components/_story.html.twig
  templates/home/index.html.twig
Labels: Reviewed
