Repository WildCodeSchool/orleans-202103-php-project-bretin, pull requests merged in 2021-07, with the labels that each got.

#107 US-36 Liste/index des cabinets à administrer
  src/Controller/CabinetController.php
  templates/Contact/People/Admin/office_index.html.twig
  templates/cabinet/index.html.twig
Labels: Reviewed

#110 US 34 Bouton suppression cabinet
  templates/cabinet/_delete_form.html.twig
  templates/cabinet/index.html.twig
Labels: Reviewed

#109 generate crud and modify file form and new
  src/Controller/EducationController.php
  src/Form/EducationType.php
  templates/education/_delete_form.html.twig
  templates/education/_form.html.twig
  templates/education/edit.html.twig
  templates/education/index.html.twig
  templates/education/new.html.twig
  templates/education/show.html.twig
  templates/home/Admin/add_education.html.twig
Labels: Corrections done, Reviewed

#112 US 17 Modification des coordonnées d'un cabinet
  src/Controller/CabinetController.php
  templates/Contact/People/Admin/edit_office.html.twig
  templates/cabinet/edit.html.twig
Labels: Reviewed

#113 edit for education
  src/Controller/EducationController.php
  templates/education/edit.html.twig
  templates/home/Admin/edit_education.html.twig
Labels: Reviewed

#115 dev to master
  src/Controller/CabinetController.php
  src/Controller/EducationController.php
  src/Form/EducationType.php
  templates/Contact/People/Admin/edit_office.html.twig
  templates/Contact/People/Admin/office_index.html.twig
  templates/cabinet/_delete_form.html.twig
  templates/cabinet/edit.html.twig
  templates/cabinet/index.html.twig
  templates/education/_delete_form.html.twig
  templates/education/_form.html.twig
  templates/education/edit.html.twig
  templates/education/index.html.twig
  templates/education/new.html.twig
  templates/education/show.html.twig
  templates/home/Admin/add_education.html.twig
  templates/home/Admin/edit_education.html.twig
  templates/home/Admin/index_education.html.twig
Labels: Reviewed

#117 add delete button
  templates/education/_delete_form.html.twig
  templates/education/index.html.twig
Labels: Reviewed

#111 Fix activity
  assets/images/strong-stone-happy.png
  assets/styles/activity.scss
  templates/Components/_activity.html.twig
Labels: Corrections done, Reviewed

#108 S5 us19 Testimony Create
  migrations/Version20210702084036.php
  migrations/Version20210704223348.php
  src/Controller/TestimonyController.php
  src/DataFixtures/TestimonyFixtures.php
  src/Entity/Testimony.php
  src/Form/TestimonyType.php
  templates/testimony/_delete_form.html.twig
  templates/testimony/_form.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
  templates/testimony/show.html.twig
Labels: Corrections done, Reviewed

#118 validion form
  src/Entity/Education.php
Labels: Corrections done, Reviewed

#120 dev to master
  assets/images/strong-stone-happy.png
  assets/styles/activity.scss
  migrations/Version20210702084036.php
  migrations/Version20210704223348.php
  src/Controller/TestimonyController.php
  src/DataFixtures/TestimonyFixtures.php
  src/Entity/Education.php
  src/Entity/Testimony.php
  src/Form/TestimonyType.php
  templates/Components/_activity.html.twig
  templates/education/_delete_form.html.twig
  templates/education/index.html.twig
  templates/testimony/_delete_form.html.twig
  templates/testimony/_form.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
  templates/testimony/show.html.twig
Labels: Reviewed

#126 Fix Testimony Mise en forme
  assets/styles/app.scss
  assets/styles/testimony.scss
  templates/testimony/index.html.twig
Labels: Reviewed

#123 update navbar link and home link
  assets/images/favicon.png
  src/Controller/HomeController.php
  src/Controller/IndividualsController.php
  templates/Includes/_accueil.html.twig
  templates/Includes/_navbar.html.twig
  templates/Individuals/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#131 generate crud et modify form and new file
  src/Controller/UserController.php
  src/Form/UserType.php
  templates/home/Admin/add_biography.html.twig
  templates/home/Admin/index_biography.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#135 suppression scroll
  assets/styles/accueil.scss
Labels: Reviewed

#139 edit form
  src/Controller/UserController.php
  templates/home/Admin/edit_biography.html.twig
  templates/user/edit.html.twig
Labels: Corrections done, Reviewed

#127 affichage services
  assets/styles/individuals.scss
  migrations/Version20210705085554.php
  src/Controller/IndividualsController.php
  src/DataFixtures/ServiceFixtures.php
  src/Entity/Service.php
  src/Repository/ServiceRepository.php
  templates/Individuals/index.html.twig
Labels: Corrections done, Reviewed

#136 Testimony Create
  src/Controller/TestimonyController.php
  src/Form/TestimonyType.php
  templates/Includes/_flashTestimony.html.twig
  templates/Individuals/Admin/add_testimony.html.twig
  templates/base.html.twig
  templates/home/Admin/add_education.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
Labels: Corrections done, Reviewed

#138 US28 uploader les photos des cabinets
  .gitignore
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210705092610.php
  migrations/Version20210706073722.php
  public/uploads/cabinet1-60e4138b7a220789630673-60e41402bd880368889740-60e42be877646386192298-60e464cfc0e32424548739.jpg
  public/uploads/cabinet2-60e42ca4e83a5631463564.jpg
  src/Controller/CabinetController.php
  src/Entity/Picture.php
  src/Form/PictureType.php
  symfony.lock
  templates/cabinet/edit_picture.html.twig
  templates/cabinet/index.html.twig
Labels: Corrections done, Reviewed

#141 delete form and validation
  src/Entity/User.php
  templates/user/_delete_form.html.twig
Labels: Reviewed

#142 index admin biography
  templates/user/index.html.twig
Labels: Reviewed

#145 Testimony Delete
  src/Controller/TestimonyController.php
  templates/testimony/_delete_form.html.twig
  templates/testimony/index.html.twig
Labels: Reviewed

#154 migration service
  migrations/Version20210707082731.php
Labels: Reviewed

#155 fix use and route of individuals
  src/Controller/IndividualsController.php
  src/Entity/User.php
Labels: Reviewed

#156 fix picture data
  .gitignore
  migrations/Version20210707085303.php
  public/uploads/.gitignore
  public/uploads/cabinet1-60e4138b7a220789630673-60e41402bd880368889740-60e42be877646386192298-60e464cfc0e32424548739.jpg
  public/uploads/cabinet2-60e42ca4e83a5631463564.jpg
  public/uploads/cabinet2.jpg
  public/uploads/cabinet21.jpg
  public/uploads/cabinet22.jpg
  public/uploads/cabinet23.jpg
  public/uploads/cabinet3.jpg
  src/DataFixtures/PictureFixtures.php
Labels: Corrections done, Reviewed

#150 fix affichage images vish page contact
  templates/Includes/_contact.html.twig
Labels: Reviewed

#144 Testimony Edit
  src/Controller/TestimonyController.php
  src/Form/TestimonyType.php
  templates/Individuals/Admin/edit_testimony.html.twig
  templates/testimony/_delete_form.html.twig
  templates/testimony/_form.html.twig
  templates/testimony/edit.html.twig
Labels: Corrections done, Reviewed

#159 Mise en Forme Testimony
  src/Form/TestimonyType.php
  templates/Individuals/Admin/add_testimony.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
Labels: Corrections done, Reviewed

#162 upload bio picture
  config/packages/vich_uploader.yaml
  migrations/Version20210707135001.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/Components/_story.html.twig
  templates/user/_delete_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#160 spelling mistake
  templates/Components/_activity.html.twig
Labels: Corrections done, Reviewed

#163 Testimony Individuals Carousel
  assets/styles/testimony.scss
  src/Controller/IndividualsController.php
  src/Controller/TestimonyController.php
  templates/Components/_testimonyIndividuals.html.twig
  templates/Includes/_contact.html.twig
  templates/Individuals/index.html.twig
Labels: Corrections done, Reviewed

#166 navbar admin and update extend for each admin index
  templates/Components/_navbar_admin.html.twig
  templates/Contact/People/Admin/office_index.html.twig
  templates/base_admin.html.twig
  templates/education/index.html.twig
  templates/home/Admin/index_biography.html.twig
  templates/home/Admin/index_education.html.twig
  templates/layout_admin.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#168 listing service admin
  src/Controller/ServiceController.php
  src/Form/ServiceType.php
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/edit.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
  templates/service/show.html.twig
Labels: Reviewed

#169 ajout service et message flash
  src/Controller/ServiceController.php
  src/Form/ServiceType.php
  templates/service/new.html.twig
Labels: Reviewed

#170 suppression service et message flash
  src/Controller/ServiceController.php
  templates/service/_delete_form.html.twig
Labels: Reviewed

#171 modification service et message flash
  src/Controller/ServiceController.php
  templates/service/edit.html.twig
Labels: Reviewed

#164 US-21 Pouvoir s'identifier via un formulaire de connexion
  composer.lock
  config/packages/security.yaml
  migrations/Version20210707130839.php
  migrations/Version20210708133447.php
  migrations/Version20210708151635.php
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/DataFixtures/AdminUserFixtures.php
  src/Entity/AdminUser.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/AdminUserRepository.php
  src/Repository/UserRepository.php
  src/Security/Authenticator.php
  templates/Includes/admin.html.twig
  templates/security/login.html.twig
Labels: Corrections done, Reviewed

#165 Page entreprises services
  assets/images/background-entreprises.jpg
  assets/images/check-circle.svg
  assets/images/clipboard-check.svg
  assets/images/hands.png
  assets/images/mbti-logo.png
  assets/images/together.jpg
  assets/images/together.png
  assets/styles/companies.scss
  src/Controller/CompaniesController.php
  templates/Companies/index.html.twig
  templates/Includes/_navbar.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#172 dev to master
  assets/images/background-entreprises.jpg
  assets/images/check-circle.svg
  assets/images/clipboard-check.svg
  assets/images/hands.png
  assets/images/mbti-logo.png
  assets/images/together.jpg
  assets/images/together.png
  assets/styles/companies.scss
  assets/styles/testimony.scss
  composer.lock
  config/packages/security.yaml
  config/packages/vich_uploader.yaml
  migrations/Version20210707130839.php
  migrations/Version20210707135001.php
  migrations/Version20210708133447.php
  migrations/Version20210708151635.php
  src/Controller/CompaniesController.php
  src/Controller/HomeController.php
  src/Controller/IndividualsController.php
  src/Controller/SecurityController.php
  src/Controller/ServiceController.php
  src/Controller/TestimonyController.php
  src/Controller/UserController.php
  src/DataFixtures/AdminUserFixtures.php
  src/Entity/AdminUser.php
  src/Entity/User.php
  src/Form/ServiceType.php
  src/Form/UserType.php
  src/Repository/AdminUserRepository.php
  src/Repository/UserRepository.php
  src/Security/Authenticator.php
  templates/Companies/index.html.twig
  templates/Components/_activity.html.twig
  templates/Components/_navbar_admin.html.twig
  templates/Components/_story.html.twig
  templates/Components/_testimonyIndividuals.html.twig
  templates/Contact/People/Admin/office_index.html.twig
  templates/Includes/_contact.html.twig
  templates/Includes/_navbar.html.twig
  templates/Includes/admin.html.twig
  templates/Individuals/index.html.twig
  templates/base_admin.html.twig
  templates/education/index.html.twig
  templates/home/Admin/index_biography.html.twig
  templates/home/Admin/index_education.html.twig
  templates/layout_admin.html.twig
  templates/security/login.html.twig
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/edit.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
  templates/service/show.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
  templates/user/_delete_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: Reviewed

#173 fonction de déconnexion
  src/Controller/SecurityController.php
  templates/Components/_navbar_admin.html.twig
  templates/Includes/admin.html.twig
Labels: Reviewed

#178 Fix form ajout cabinet, traduction des étiquettes de champs en français
  templates/cabinet/new.html.twig
Labels: Reviewed

#179 Fix mise en page form edit office
  templates/cabinet/edit.html.twig
Labels: Reviewed

#180 US-45 Fonction mot de passe oublié - Reset admin password
  src/Controller/UserController.php
  src/DataFixtures/AdminUserFixtures.php
  src/Entity/Account.php
  src/Form/AccountType.php
  templates/security/login.html.twig
  templates/user/new_password.html.twig
Labels: Reviewed

#182 fix ecartement boutons page admin
  templates/Includes/admin.html.twig
Labels: Reviewed

#181 fix form upload photo mise en page
  templates/cabinet/edit_picture.html.twig
Labels: Reviewed

#186 Fix footer formatting and responsive
  templates/Includes/_footer.html.twig
Labels: Reviewed

#184 Securisation routes admin
  config/packages/security.yaml
  src/Controller/CabinetController.php
  src/Controller/EducationController.php
  src/Controller/ServiceController.php
  src/Controller/TestimonyController.php
  src/Controller/UserController.php
Labels: Reviewed

#187 Fix tri nom crud services
  src/Controller/ServiceController.php
Labels: Corrections done, Reviewed

#188 Lien bouton entreprises
  templates/Includes/_accueil.html.twig
Labels: Reviewed

#190 fix bug user
  src/Controller/UserController.php
Labels: Reviewed

#183 S06 us47 bannières espace particuliers
  assets/images/background-particuliers.jpg
  assets/styles/companies.scss
  assets/styles/individuals.scss
  templates/Companies/index.html.twig
  templates/Individuals/index.html.twig
Labels: Corrections done, Reviewed

#192 Fix testimony Edit
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
Labels: Reviewed

#193 S6 us13 sendform
  composer.lock
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  templates/Components/email.html.twig
  templates/Contact/People/contact.html.twig
  templates/Includes/_contact_business.html.twig
Labels: Corrections done, Reviewed

#185 Fix navbar target
  assets/styles/accueil.scss
  assets/styles/app.scss
  templates/Includes/_navbar.html.twig
Labels: Reviewed

#194 DEV TO MASTER
  assets/images/background-particuliers.jpg
  assets/styles/accueil.scss
  assets/styles/app.scss
  assets/styles/companies.scss
  assets/styles/individuals.scss
  composer.lock
  config/packages/security.yaml
  config/services.yaml
  src/Controller/CabinetController.php
  src/Controller/ContactController.php
  src/Controller/EducationController.php
  src/Controller/SecurityController.php
  src/Controller/ServiceController.php
  src/Controller/TestimonyController.php
  src/Controller/UserController.php
  src/DataFixtures/AdminUserFixtures.php
  src/Entity/Account.php
  src/Entity/Contact.php
  src/Entity/Service.php
  src/Entity/Testimony.php
  src/Form/AccountType.php
  src/Form/ContactType.php
  src/Form/TestimonyType.php
  templates/Companies/index.html.twig
  templates/Components/_navbar_admin.html.twig
  templates/Components/email.html.twig
  templates/Contact/People/contact.html.twig
  templates/Includes/_accueil.html.twig
  templates/Includes/_contact_business.html.twig
  templates/Includes/_footer.html.twig
  templates/Includes/_navbar.html.twig
  templates/Includes/admin.html.twig
  templates/Individuals/index.html.twig
  templates/cabinet/edit.html.twig
  templates/cabinet/edit_picture.html.twig
  templates/cabinet/new.html.twig
  templates/security/login.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/user/new_password.html.twig
Labels: Reviewed

#204 Fix reformulation phrase
  src/DataFixtures/AdminUserFixtures.php
Labels: Reviewed

#205 Crud bio modif
  templates/user/edit.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#206 Fix admin navigation services
  templates/Components/_navbar_admin.html.twig
  templates/service/_delete_form.html.twig
  templates/service/edit.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
Labels: Reviewed

#207 insertion navbar_admin
  templates/Contact/People/Admin/add_office.html.twig
  templates/Contact/People/Admin/edit_office.html.twig
  templates/Contact/People/contact.html.twig
  templates/Individuals/Admin/add_testimony.html.twig
  templates/Individuals/Admin/edit_testimony.html.twig
  templates/cabinet/_delete_form.html.twig
  templates/cabinet/edit.html.twig
  templates/cabinet/index.html.twig
  templates/cabinet/new.html.twig
  templates/education/_delete_form.html.twig
  templates/education/_form.html.twig
  templates/education/edit.html.twig
  templates/education/index.html.twig
  templates/education/new.html.twig
  templates/testimony/_delete_form.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
Labels: Reviewed

#208 Fix footer img text and size
  assets/images/loic-footer.png
  templates/Includes/_footer.html.twig
Labels: Reviewed

#209 Fix reset password
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20210715082037.php
  phpstan.neon
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#214 fix horizontal scroll and navbar
  templates/Contact/People/contact.html.twig
Labels: Reviewed

#213 mise à jour style et img page entreprises
  assets/images/desk.webp
  assets/images/hands.jpg
  assets/images/plant.webp
  assets/styles/companies.scss
  templates/Companies/index.html.twig
Labels: Reviewed

#211 fix flash message and nullable field
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  templates/Includes/_contact_business.html.twig
Labels: Corrections done, Reviewed

#212 update readme
  README.md
Labels: Reviewed

#216 Fix footer titles size
  templates/Includes/_footer.html.twig
Labels: Reviewed

#217 DEV TO MASTER
  README.md
  assets/images/desk.webp
  assets/images/hands.jpg
  assets/images/loic-footer.png
  assets/images/plant.webp
  assets/styles/companies.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20210715082037.php
  phpstan.neon
  src/Controller/ContactController.php
  src/Controller/ResetPasswordController.php
  src/DataFixtures/AdminUserFixtures.php
  src/Entity/Contact.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ContactType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/Companies/index.html.twig
  templates/Components/_navbar_admin.html.twig
  templates/Contact/People/Admin/add_office.html.twig
  templates/Contact/People/Admin/edit_office.html.twig
  templates/Contact/People/contact.html.twig
  templates/Includes/_contact_business.html.twig
  templates/Includes/_footer.html.twig
  templates/Individuals/Admin/add_testimony.html.twig
  templates/Individuals/Admin/edit_testimony.html.twig
  templates/cabinet/_delete_form.html.twig
  templates/cabinet/edit.html.twig
  templates/cabinet/index.html.twig
  templates/cabinet/new.html.twig
  templates/education/_delete_form.html.twig
  templates/education/_form.html.twig
  templates/education/edit.html.twig
  templates/education/index.html.twig
  templates/education/new.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  templates/service/_delete_form.html.twig
  templates/service/edit.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
  templates/testimony/_delete_form.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#220 fix alignement rubrique activité
  templates/Components/_activity.html.twig
Labels: Reviewed

#210 Fix routes fr
  src/Controller/CabinetController.php
  src/Controller/EducationController.php
  src/Controller/SecurityController.php
  src/Controller/ServiceController.php
  src/Controller/TestimonyController.php
  src/Controller/UserController.php
Labels: Reviewed

#218 fix padding h2 page entreprise
  templates/Companies/index.html.twig
Labels: Reviewed

#221 DEV TO MASTER
  src/Controller/CabinetController.php
  src/Controller/EducationController.php
  src/Controller/SecurityController.php
  src/Controller/ServiceController.php
  src/Controller/TestimonyController.php
  src/Controller/UserController.php
  templates/Companies/index.html.twig
  templates/Components/_activity.html.twig
Labels: Reviewed

#222 fix responsive page contact
  templates/Includes/_contact.html.twig
  templates/Includes/_contact_business.html.twig
Labels: Reviewed

#224 fix logo suppression de la partie illisible
  assets/images/Logo_L.Bretinrogn.png
  assets/images/logo.png
Labels: Reviewed

#219 Fix individuals formatting all
  assets/images/iconmonstr-angel-left-circle-thin.svg
  assets/images/iconmonstr-angel-right-circle-thin.svg
  assets/styles/individuals.scss
  assets/styles/testimony.scss
  composer.json
  composer.lock
  package-lock.json
  package.json
  templates/Components/_testimonyIndividuals.html.twig
  templates/Individuals/index.html.twig
  yarn.lock
Labels: Reviewed

#225 Fix Individuals titles
  templates/Individuals/index.html.twig
Labels: Reviewed

#226 Fix_Accueil_Responsive
  templates/Includes/_accueil.html.twig
Labels: Reviewed

#228 Fix nav
  templates/Includes/_navbar.html.twig
Labels: Reviewed

#227 Fix Homepage Responsive
  templates/Includes/_accueil.html.twig
Labels: Reviewed

#229 icons_modif
  assets/images/icon_symbole.png
  assets/images/icon_symbole1.png
  assets/styles/companies.scss
  templates/Companies/index.html.twig
Labels: Reviewed

#231 fix form contact
  src/Form/ContactType.php
  templates/Contact/People/contact.html.twig
  templates/Includes/_contact.html.twig
  templates/Includes/_contact_business.html.twig
Labels: Conflit résolu, Reviewed

#230 Modifs sections et backgrounds
  assets/styles/activity.scss
  assets/styles/story.scss
  templates/home/index.html.twig
Labels: Reviewed

#232 fix contact ajout bouton rendez-vous
  assets/images/info-circle.svg
  templates/Includes/_contact.html.twig
Labels: Reviewed

#233 fix_bold_words
  src/DataFixtures/AdminUserFixtures.php
  templates/Companies/index.html.twig
  templates/Components/_activity.html.twig
  templates/Individuals/index.html.twig
Labels: Reviewed

#235 fix_modif_font_titles
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/variables.scss
  templates/Companies/index.html.twig
  templates/Components/_testimonyIndividuals.html.twig
  templates/Includes/_contact.html.twig
  templates/Individuals/index.html.twig
Labels: Reviewed

#236 suppression_section_dupplicate
  templates/Individuals/index.html.twig
Labels: Reviewed

#237 fix_size_navbar
  assets/styles/app.scss
  templates/Includes/_navbar.html.twig
Labels: Reviewed

#239 Bug Vish Upload Mise en Prod
  public/LB.jpg
  src/Controller/HomeController.php
  src/Entity/AdminUser.php
  templates/Components/_story.html.twig
Labels: Reviewed

#241 update error page
  assets/styles/error.scss
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  webpack.config.js
Labels: Reviewed

#240 fix_styles_font_crud
  assets/styles/companies.scss
  assets/styles/education.scss
  assets/styles/story.scss
  src/DataFixtures/AdminUserFixtures.php
  templates/Companies/index.html.twig
  templates/Components/_education.html.twig
  templates/Contact/People/Admin/add_office.html.twig
  templates/Contact/People/Admin/edit_office.html.twig
  templates/Contact/People/Admin/office_index.html.twig
  templates/Individuals/Admin/edit_testimony.html.twig
  templates/home/Admin/add_education.html.twig
  templates/home/Admin/edit_biography.html.twig
  templates/home/Admin/edit_education.html.twig
  templates/home/Admin/index_biography.html.twig
  templates/home/Admin/index_education.html.twig
  templates/security/login.html.twig
  templates/user/edit.html.twig
Labels: Corrections done, Reviewed

#243 update contact form
  src/Form/ContactType.php
  templates/Includes/_contact.html.twig
  templates/Includes/_contact_business.html.twig
Labels: Reviewed

#242 footer
  src/Controller/HomeController.php
  templates/Includes/_footer.html.twig
Labels: Reviewed

#246 Fix offices
  src/Controller/CompaniesController.php
  src/Controller/IndividualsController.php
Labels: Reviewed

#247 CGU
  assets/styles/footer.scss
  src/Controller/CguController.php
  templates/Includes/_footer.html.twig
  templates/cgu/index.html.twig
Labels: Reviewed

#248 fix variables
  assets/styles/companies.scss
  assets/styles/contact.scss
  assets/styles/individuals.scss
Labels: Reviewed

#250 Ajout pics
  src/Controller/CabinetController.php
  src/Entity/Office.php
  src/Entity/Picture.php
  templates/cabinet/_delete_pic.html.twig
  templates/cabinet/edit_picture.html.twig
  templates/cabinet/index.html.twig
Labels: Reviewed

#251 dev to master !
  src/Controller/CabinetController.php
  src/Entity/Office.php
  src/Entity/Picture.php
  templates/cabinet/_delete_pic.html.twig
  templates/cabinet/edit_picture.html.twig
  templates/cabinet/index.html.twig
Labels: Reviewed

#252 update mentions
  templates/cgu/index.html.twig
Labels: Reviewed
